[tool.poetry]
name = "gatorgrade"
version = "0.1.0"
description = ""
authors = ["Lauren Nevill <nevill01@allegheny.edu>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
taskipy = "^1.10.1"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pylint = "^2.13.4"

[tool.taskipy.tasks]
test = "pytest --cov-report term-missing --cov-fail-under=70  --cov-branch --cov=package tests/"
lint = "pylint package/ tests/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
